version: '3.3'

volumes:
  pg_data:

networks:
  wallet_net:
    driver: overlay

services:
  pg:
    restart: always
    image: postgres:10.1-alpine
    environment:
      - POSTGRES_PASSWORD=eiphiishooShaeBoh7biYem0joh3sho4
      - POSTGRES_DB=wallet
    networks:
      - wallet_net
    volumes:
      - pg_data:/var/lib/postgresql/data
    deploy:
      placement:
        constraints: [node.hostname == squarex-dev-venus]
  app:
    restart: always
    image: randomnerd/wallet:latest
    environment:
      - DB_PASSWORD=eiphiishooShaeBoh7biYem0joh3sho4
    ports:
      - '3131:3000'
    networks:
      - wallet_net
#    deploy:
#      placement:
#        constraints: [node.hostname == squarex-dev-venus]

